# Generated by Django 4.0.4 on 2022-04-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postings.posting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
