# Generated by Django 4.0.4 on 2022-04-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
