# Generated by Django 4.0.4 on 2022-04-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_alter_like_posting_alter_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Posting_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.tag')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.posting')),
            ],
            options={
                'db_table': 'Posting_Tags',
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='postings', through='postings.Posting_Tag', to='postings.tag'),
        ),
    ]
