# Generated by Django 4.0.4 on 2022-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_tag_posting_tag_posting_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='_postings', through='postings.Posting_Tag', to='postings.tag'),
        ),
    ]
