# Generated by Django 4.0.4 on 2022-04-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_alter_posting_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
